name: Deploy SIMLK Backend
on:
  push:
    branches: [master]
jobs:
  web-deploy:
    name: 🎉 Deploy SIMLK Backend
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📁 Send files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.SSH_USERNAME }}
            server: ${{ secrets.SSH_HOST }}
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
            local_path: './*'
            remote_path: '/home/bemfilkomv2/BE_WEB_BEM_Proker'

      - name: 🌟 Run server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo pm2 delete BE_WEB_BEM_Proker
            cd /home/bemfilkomv2/BE_WEB_BEM_Proker
            go build .
            sudo pm2 start ./BE_WEB_BEM_Proker
